"""
Each new term in the Fibonnaci sequence is generated by adding the previos
two terms. By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89
By considering the terms in the Fibonnaci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
"""

def fibonacci():
    fibonacci_sequence = [1, 2]
    while sum(fibonacci_sequence) < 4000000:
        next_number = fibonacci_sequence[-1] + fibonacci_sequence[-2]
        fibonacci_sequence.append(next_number)
    
    return sum(fibonacci_sequence)

#########################   Main    ################################

print(fibonacci())