"""
Each new term in the Fibonnaci sequence is generated by adding the previos
two terms. By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89
By considering the terms in the Fibonnaci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
"""

import numpy

def fibonacci(number1= 1, number2= 2, sum_fibonacci = 0):
    if number2 >= 4000000:
        return sum_fibonacci
    elif number2 % 2 == 0:
        sum_fibonacci += number2
    
    return fibonacci(number1= number2, number2= number1 + number2, sum_fibonacci= sum_fibonacci)

#########################   Main    ################################

print(fibonacci())